project:
  type: website

website:
  title: "ISSS608-VAA-PROJECT"
  navbar:
    left:
      - text: "Proposal"
        href: "Proposal/Proposal.html"
      - text: "Prototype"
        href: "Prototype/Prototype.html"
      - text: "Poster"
        href: "Poster/Poster.html"
      - text: "User Guide"
        href: "User Guide/User_guide.html"
      - text: "Shiny App"
        href: "https://haductien1211.shinyapps.io/MC3ShinyAppDemo/"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: default
      dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    grid: 
      body-width: 1500px
      sidebar-width: 300px
      margin-width:	150px

editor: visual